### PR TITLE
Hungarian language support for blackPanther OS

### PR DESCRIPTION
**Pull request by blackPantherOS**
Hi, 
I've added initial Hungarian translations for your project but I can't test translations because latest git version started but does not displaying main window and I get empty window in systemsettings as well.
Cheers

### CODE REVIEW

**Comment by Maldela** [comment]
Thanks, that's great. Please try `fancontrol_gui` in a terminal and tell me what it says.

**Comment by blackPantherOS** [comment]
> Thanks, that's great. Please try `fancontrol_gui` in a terminal and tell me what it says.
Sure I tried, nothing ... just running without any verbose output or any message. 0.6 working but I like it the plasmoid support idea and tray support too

**Comment by Maldela** [comment]
Nothing at all? Does it print anything if you type 'fancontrol_gui -h' or 'kcmshell5 fancontrol-kcm'?

**Comment by blackPantherOS** [comment]
Sorry my response is too late, we working on next blackPanther release out...
So, nothing get was output, or does not get any error message.
I'll build a new binary in debug mode and I will double check again the latest source from your git. I need some days to get my free time

**Pull request merged**
